# Generated by Django 3.0.8 on 2022-08-12 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20220813_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satmodel',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satmodel', to='search.Sector'),
        ),
        migrations.AlterField(
            model_name='satmodel',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satmodel', to='search.Variables'),
        ),
    ]
