# Generated by Django 3.0.8 on 2022-08-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20220813_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satmodel',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='satmodel',
            name='unit',
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Climate', 'Climate'), ('Energy', 'Energy'), ('Land', 'Land'), ('Socio-economic', 'Socio-economic')], max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=100)),
                ('longname', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variable', to='search.Sector')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='search.Unit')),
            ],
        ),
        migrations.AlterField(
            model_name='satmodel',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satmodel', to='search.Variable'),
        ),
        migrations.DeleteModel(
            name='Variables',
        ),
    ]
