# Generated by Django 3.2.4 on 2022-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20220815_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satmodel',
            old_name='satellite_or_model',
            new_name='satellite_or_model_short',
        ),
        migrations.AddField(
            model_name='satmodel',
            name='satellite_or_model_long',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
