# Generated by Django 3.2.4 on 2022-08-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20220818_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='satmodel',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='satmodel', to='search.sector'),
        ),
    ]
