# Generated by Django 3.2.4 on 2022-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_satmodel_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satmodel',
            name='reference',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
