# Generated by Django 3.2.4 on 2022-08-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_satmodel_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satmodel',
            name='sector',
        ),
    ]
