# Generated by Django 3.2.4 on 2022-08-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_alter_variable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='search.unit'),
        ),
    ]
